CREATE TABLE If NOT EXISTS customer(
    Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Name VARCHAR(250) NOT NULL,
    Email VARCHAR(250) NOT NULL,
    Created_at TIMESTAMP DEFAULT NOW(),
    Updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW()
);