CREATE TABLE IF NOT EXISTS orderitem(
    Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Order_id INT NOT NULL, 
    Item_id INT NOT NULL,
    Created_at TIMESTAMP DEFAULT NOW(),
    Updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW(),
    FOREIGN KEY(Order_id) REFERENCES orders(Id) ON DELETE CASCADE,
    FOREIGN KEY(Item_id) REFERENCES menu(Id) ON DELETE CASCADE
);